# Generated by Django 5.0.4 on 2024-04-19 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_description'),
        ('enrollments', '0002_alter_enroll_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='created_at',
            new_name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='enroll',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
